In [13]:
d=np.arange(12).reshape(6,2)
print("d:")
print(d)
d1,d2 = np.split(d, 2)
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [2]:
import numpy as np

d=np.arange(12).reshape(2,6)
print("d:")
print(d)
parts=np.split(d, (2,3,5), axis=1)
parts[0]

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([[0, 1],
       [6, 7]])

In [23]:
a=np.array([[4,5,7],[9,6,8]])
#print(len(a[1])) # number of columns
#print(len(a)) # number of rows

In [28]:
def get_row_vectors( name, matrix ):
    parts= np.split( matrix, len(matrix), axis=0 )
    print("For the matrix ", name, " the row vectors are as follows \n" )
    return parts
get_row_vectors("A",a)

For the matrix  A  the row vectors are as follows 



[array([[4, 5, 7]]), array([[9, 6, 8]])]

In [29]:
def get_column_vectors( name, matrix ):
    parts= np.split( matrix, len(matrix[1]), axis=1)
    print("For the matrix", name, "the column vectors are as follows \n")
    return parts
get_column_vectors("A", a)

For the matrix A the column vectors are as follows 



[array([[4],
        [9]]),
 array([[5],
        [6]]),
 array([[7],
        [8]])]

In [85]:
dim=int(input())
p=np.full((dim+2,dim+2), fill_value=0)
p

3


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [83]:
print(int(len(p)/2))

3


In [86]:
p[0][dim-1]=1

i=1
l=1
dim=dim-1
border=int(len(p)/2)+1

while i < border:
    p[i][dim-l]=1
    p[i][dim+l]=1

    l=l+1
    i=i+1
last_dim_back=dim-1
last_dim_on=dim+1
p        

array([[0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [87]:
print(border)
print(last_dim_back, last_dim_on)

3
1 3


In [88]:
while border < len(p)-1:
      l=l-1
      
      p[border][last_dim_back]=1
      p[border][last_dim_on]=1
    
      last_dim_back=last_dim_back+1
      last_dim_on=last_dim_on-1
    
      border=border+1

p[len(p)-1][dim]=1

p

array([[0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [111]:
#Exercise 14

d=np.arange(12).reshape(4,3)
print(d)
print("\n")
d=d*d
print(d)
print("\n")
s=np.sum(d,axis=1)
print(s)
print("\n")
t=np.sqrt(s)
print(t)
print("\n")
t=np.array(t)
t.shape
#t=get_column_vectors(s)
#print("T",t)
#farrays=get_row_vectors("D",d)

# 4 rows
# 3 columns
# the shape is (4,3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


[  5  50 149 302]


[ 2.23606798  7.07106781 12.20655562 17.3781472 ]




(4,)